set(_CATKIN_CURRENT_PACKAGE "odomtopic")
set(odomtopic_VERSION "0.0.0")
set(odomtopic_MAINTAINER "akif <akif@todo.todo>")
set(odomtopic_PACKAGE_FORMAT "2")
set(odomtopic_BUILD_DEPENDS "roscpp" "rospy" "message_generation")
set(odomtopic_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(odomtopic_BUILDTOOL_DEPENDS "catkin")
set(odomtopic_BUILDTOOL_EXPORT_DEPENDS )
set(odomtopic_EXEC_DEPENDS "roscpp" "rospy" "message_runtime")
set(odomtopic_RUN_DEPENDS "roscpp" "rospy" "message_runtime")
set(odomtopic_TEST_DEPENDS )
set(odomtopic_DOC_DEPENDS )
set(odomtopic_URL_WEBSITE "")
set(odomtopic_URL_BUGTRACKER "")
set(odomtopic_URL_REPOSITORY "")
set(odomtopic_DEPRECATED "")